# Generated by Django 5.1.3 on 2024-11-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file_type', models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video')], default='Photo', max_length=10)),
                ('location', models.CharField(choices=[('Off-campus', 'Off-campus'), ('On-campus', 'On-campus')], max_length=20)),
                ('event_type', models.CharField(choices=[('Award', 'Award'), ('Seminar', 'Seminar'), ('Performance', 'Performance'), ('Conference', 'Conference'), ('Speech', 'Speech'), ('Pickup', 'Pickup'), ('Cultural', 'Cultural'), ('Cultural Experience', 'Cultural Experience'), ('Booth', 'Booth'), ('Corporate Trip', 'Corporate Trip'), ('Others', 'Others')], max_length=20)),
                ('camera_shot', models.CharField(blank=True, choices=[('Long Shot', 'Long Shot'), ('Close Shot', 'Close Shot'), ('Medium Shot', 'Medium Shot'), (None, 'null')], max_length=20, null=True)),
                ('camera_angle', models.CharField(blank=True, choices=[('Back', 'Back'), ('Front', 'Front'), ('Side', 'Side'), ('High-angle', 'High-angle'), ('Low-angle', 'Low-angle'), (None, 'null')], max_length=20, null=True)),
                ('atmosphere', models.CharField(blank=True, choices=[('Not recognized', 'Not recognized'), ('Positive', 'Positive'), ('Joyful', 'Joyful'), ('Serious', 'Serious'), ('Interactive', 'Interactive'), (None, 'null')], max_length=20, null=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Chinese', 'Chinese'), ('Other', 'Other')], default='English', max_length=10)),
                ('race', models.CharField(choices=[('White', 'White'), ('Asian', 'Asian'), ('Afro', 'Afro'), ('Other', 'Other')], default='Other', max_length=10)),
                ('date', models.DateField(default='2024-01-01')),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
