# Generated by Django 5.1.5 on 2025-01-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='race',
            field=models.CharField(choices=[('IBA', 'IBA'), ('IPAI', 'IPAI'), ('ITH', 'ITH'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
